<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>OscarWatch.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OscarWatch.Ft4.Core\OscarWatch.Ft4.Core.csproj" />
  </ItemGroup>
</Project>
